version: "3.9"

services:
  clonebot:
    image: arata74/clonebot 
    #ghcr.io/thecaduceus/cbv2:main
    container_name: clonebot
    environment:
      - CONFIG_FILE_URL=${CONFIG_FILE_URL}
    ports:
      - 8080:8080
    restart: unless-stopped
